version: '3'
services:
  web:
    build: .
    tty: true
    volumes:
      - '.:/app'
    working_dir: /app
  db:
    image: mysql:5.7.35
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
  https:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://web:80'
